### ISSUE TITLE
Cannot find my gateway

### ISSUE THREAD

**Issue by i00** [briis/smartweatherudp#19]
I have a Tempest and am using the gateway that came with it ...

I can ping my weather flow gateway, but when I try to use this in HA I get:

```
2020-12-17 18:32:55 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smartweatherudp platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartweatherudp/sensor.py", line 71, in setup_platform
    module = SWReceiver(config.get(CONF_HOST), DEFAULT_PORT, unit_system)
  File "/usr/local/lib/python3.8/site-packages/pysmartweatherudp/receiver.py", line 35, in __init__
    self._socket.bind((host, port))
OSError: [Errno 99] Address not available
```

###Config
```yaml
sensor:
  - platform: smartweatherudp
    host: WeatherFlow.local
    wind_unit: kmh
    name: weatherflow_bowler
```

I have tried both with IP and my local DNS name for it.

**Comment by skippy-oz** [comment]
I have the same problem

**Comment by LuckyJayDIY** [comment]
I seem to remember either having this issue myself or helping someone else a few months back - 

Try taking the host: line out of your configuration.

**Comment by skippy-oz** [comment]
@LuckyJayDIY  Thanks for that. It's working now

**Comment by LuckyJayDIY** [comment]
Yeah, the hub broadcasts on your network with UDP packets on port 50222 and UDP is a non-connected protocol so you don't need a host address.

**Comment by i00** [comment]
Ok ... that fixed it ... well for a while ... worked for about a week then just stopped... any ideas?

Thanks

**Comment by i00** [comment]
Ok ... for some reason it started picking up readings when I reset the device.
