### ISSUE TITLE
Error while setting up smartweatherudp platform for sensor

### ISSUE THREAD

**Issue by VoetenK** [briis/smartweatherudp#23]
Logger: homeassistant.components.sensor
Source: custom_components/smartweatherudp/sensor.py:71
Integration: Sensor (documentation, issues)
First occurred: 3:13:05 PM (1 occurrences)
Last logged: 3:13:05 PM

Error while setting up smartweatherudp platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartweatherudp/sensor.py", line 71, in setup_platform
module = SWReceiver(config.get(CONF_HOST), DEFAULT_PORT, unit_system)
File "/usr/local/lib/python3.8/site-packages/pysmartweatherudp/receiver.py", line 35, in init
self._socket.bind((host, port))
socket.gaierror: [Errno -2] Name does not resolve

**Comment by michaelstein60** [comment]
Just installed and I’m seeing the same issue.

2021-02-09 15:04:17 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smartweatherudp platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartweatherudp/sensor.py", line 71, in setup_platform
module = SWReceiver(config.get(CONF_HOST), DEFAULT_PORT, unit_system)
File "/usr/local/lib/python3.8/site-packages/pysmartweatherudp/receiver.py", line 35, in __init__
self._socket.bind((host, port))
OSError: [Errno 99] Address not available

**Comment by motoridersd** [comment]
Did you use something other than 0.0.0.0 where it says host? If you did, try changing to the default. I assumed I had to use my hub's IP, but since the integration listens for broadcast UDP packets, you don't set an IP here.

**Comment by VoetenK** [comment]
Where can I change the default settings?

**Comment by motoridersd** [comment]
I meant change it back to 0.0.0.0. Just copy the config text as is and don't edit anything.

**Comment by VoetenK** [comment]
Sorry, I feel stupid. I do not know what you mean.
I added the integration, entered my token and my station id.
All my 33 sensors are available, but I still get the error message.

**Comment by natekspencer** [comment]
If this is still an issue after upgrading to v2021.12.0, please open a new issue.
