### ISSUE TITLE
No sensors found after upgrade

### ISSUE THREAD

**Issue by chheiss** [briis/smartweatherudp#41]
After the switch to UI based config flow, all tempest sensors are unavailable. A new setup brings just the base station, but all tempest sensors are gone.
Cloud based integration works.

**Comment by natekspencer** [comment]
Please update to the latest version (2021.12.3) and enable debugging for `custom_components.smartweatherudp` and `pyweatherflowudp` in your configuration.yaml file:
```yaml
logger:
  default: warning
  logs:
    custom_components.smartweatherudp: debug
    pyweatherflowudp: debug
```

Restart Home Assistant, and then look in your logs to see if there are any errors.
[![Open your Home Assistant instance and show your Home Assistant logs.](https://my.home-assistant.io/badges/logs.svg)](https://my.home-assistant.io/redirect/logs/)

Ideally, you should see an entry for your hub and each sensor, the first one being "Found a device: ..." and the second being "Adding sensors for ...". It may take a minute for the sensors to show up.

Additionally, please let me know the HA version you are on. The minimum supported version of Home Assistant is 2021.11 because of the entity categories. So if you aren't on that, you will probably see errors in your logs.

**Comment by chheiss** [comment]
HA and integration up to date, as always...

**Comment by chheiss** [comment]
2021-12-13 21:14:24 DEBUG (MainThread) [pyweatherflowudp.client] Started listening
2021-12-13 21:14:25 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197340,"rssi":-51,"timestamp":1639426464,"reset_flags":"PIN,SFT,HRDFLT","seq":19721,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'
2021-12-13 21:14:25 DEBUG (MainThread) [pyweatherflowudp.client] Stopped listening
2021-12-13 21:14:25 DEBUG (MainThread) [pyweatherflowudp.client] Started listening
2021-12-13 21:14:35 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197350,"rssi":-50,"timestamp":1639426474,"reset_flags":"PIN,SFT,HRDFLT","seq":19722,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'
2021-12-13 21:14:35 DEBUG (MainThread) [custom_components.smartweatherudp] Found a device: Hub<serial_number=HB-00045223>
2021-12-13 21:14:35 DEBUG (MainThread) [custom_components.smartweatherudp.sensor] Adding sensors for Hub<serial_number=HB-00045223>


2021-12-13 21:14:45 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197360,"rssi":-50,"timestamp":1639426484,"reset_flags":"PIN,SFT,HRDFLT","seq":19723,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'
2021-12-13 21:14:49 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.1.108/data.jsn failed with All connection attempts failed
2021-12-13 21:14:55 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197370,"rssi":-50,"timestamp":1639426494,"reset_flags":"PIN,SFT,HRDFLT","seq":19724,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'
2021-12-13 21:15:05 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197380,"rssi":-50,"timestamp":1639426504,"reset_flags":"PIN,SFT,HRDFLT","seq":19725,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'
2
2021-12-13 21:15:15 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197390,"rssi":-49,"timestamp":1639426514,"reset_flags":"PIN,SFT,HRDFLT","seq":19726,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'
2021-12-13 21:15:19 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://192.168.1.108/data.jsn failed with All connection attempts failed
2021-12-13 21:15:25 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197400,"rssi":-50,"timestamp":1639426524,"reset_flags":"PIN,SFT,HRDFLT","seq":19727,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'
2021-12-13 21:15:35 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197410,"rssi":-50,"timestamp":1639426534,"reset_flags":"PIN,SFT,HRDFLT","seq":19728,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'

2021-12-13 21:15:45 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197420,"rssi":-49,"timestamp":1639426544,"reset_flags":"PIN,SFT,HRDFLT","seq":19729,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'

2021-12-13 21:15:55 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197430,"rssi":-51,"timestamp":1639426554,"reset_flags":"PIN,SFT,HRDFLT","seq":19730,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'
2021-12-13 21:16:05 DEBUG (MainThread) [pyweatherflowudp.client] Received message from 192.168.1.176:50222 - b'{"serial_number":"HB-00045223","type":"hub_status","firmware_revision":"171","uptime":197440,"rssi":-51,"timestamp":1639426564,"reset_flags":"PIN,SFT,HRDFLT","seq":19731,"fs":[1,0,15675411,524288],"radio_stats":[25,1,0,3,39214],"mqtt_stats":[10,2]}'

**Comment by natekspencer** [comment]
So from what I'm seeing from that log, your Tempest isn't currently communicating with your hub. There's no events from it coming in on the UDP port. You should be seeing `rapid_wind` or `obs_st` events, but none of those are listed. Without those, the component is unaware of the existence of a Tempest device (or any other sensor) and won't create them. As such, the devices will appear as unavailable.

**Comment by chheiss** [comment]
Well, that seems to be the problem! It is communicating, it is showing live data in the app and through the cloud integration. Just not via your UDP integration.

**Comment by chheiss** [comment]
By the way, I am currently running (as of 2 minutes ago) an openhab installation that is showing the UDP live data as well. So it is definitely the HA integration that is causing the problem.

**Comment by natekspencer** [comment]
I'm admittedly perplexed. Your hub is, appropriately, sending messages via UDP about its own status. But it's not broadcasting any other updates via the same way. Or, if it is, they're somehow getting dropped. I have 2 RPis that are running this code, as well as my mac, that all work without a hitch. My network is pretty simple, no subnets or anything. So it's hard to tell if there is something else going on.

**Comment by natekspencer** [comment]
What OpenHAB installation are you running?

**Comment by natekspencer** [comment]
It's also curious, because the communication with the devices didn't change since you reported this issue: https://github.com/briis/smartweatherudp/issues/39. Which seems to indicate you were able to upgrade to the new package initially and had sensor data. Did you previously use a different "host"? Since I noticed you commenting something about only being able to get "0.0.0.0" to work.

**Comment by chheiss** [comment]
Host was always 0.0.0.0, as other hosts do not work. Same at the friend's site.

**Comment by chheiss** [comment]
openhab V3.1, they have a smartweather udp integration as well. Working good.

**Comment by djhopkins2** [comment]
I just updated from HA 2021.11 to 2021.12.x (latest) and mine quit updating too... It was working right before the HA update.

Does line 5 here have anything to do with it?
https://github.com/briis/smartweatherudp/blob/6c4deae3ad45f03f45da686e172019ca407677b8/hacs.json

**Comment by djhopkins2** [comment]
I appear to have fixed it. I was adding the logging lines to my config.yaml and saw something.
I still had an entry for this as a sensor in config.yaml. I removed it and restarted and that seemed to fix it. It wasn't an issue before.

`#sensor:
#  - platform: smartweatherudp`

**Comment by natekspencer** [comment]
> Does line 6 here have anything to do with it?

This should have no effect on Home Assistant. It simply tells HACS what the minimum version of Home Assistant is needed to be able to install the integration, so Home Assistant itself never sees it.

> I still had an entry for this as a sensor in config.yaml. I removed it and restarted and that seemed to fix it. It wasn't an issue before.

This also shouldn't cause an issue. It would result in a warning and then skip over it if already imported

**Comment by scstraus** [comment]
I'm having the same issue. Here's the error from the log:

```


Logger: homeassistant.config_entries
Source: helpers/entity_component.py:162
First occurred: 16:59:04 (10 occurrences)
Last logged: 17:08:14
Error setting up entry smartweatherudp for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 204, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 162, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

```

**Comment by Gibby** [comment]
I thought it was just me having this issue, but I guess not. Has anyone tried downgrading to see if it is resolved?

**Comment by Gibby** [comment]
On another note, I switched to https://github.com/briis/hass-weatherflow2mqtt and it is working fine.

**Comment by natekspencer** [comment]
> On another note, I switched to https://github.com/briis/hass-weatherflow2mqtt and it is working fine.

This is interesting since it uses the exact same library in both. Do you get the same "ValueError: Config entry has already been setup!"?

**Comment by Gibby** [comment]
> > On another note, I switched to https://github.com/briis/hass-weatherflow2mqtt and it is working fine.
> 
> This is interesting since it uses the exact same library in both. Do you get the same "ValueError: Config entry has already been setup!"?

Nope, no errors. Been working great.
