### ISSUE TITLE
Fails to load after latest HA updates

### ISSUE THREAD

**Issue by beaulebens** [briis/smartweatherudp#58]
I've just updated my HA instance and this component appears to no longer load. I turned on error logging and see

```
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 5:57:24 PM (1 occurrences)
Last logged: 5:57:24 PM

Detected blocking call to import_module with args ('custom_components.smartweatherudp',) in /usr/src/homeassistant/homeassistant/loader.py, line 1074: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
```

Also this one:

```
Logger: homeassistant.loader
Source: loader.py:1074
First occurred: 5:57:24 PM (2 occurrences)
Last logged: 5:57:24 PM

Unexpected exception importing component custom_components.smartweatherudp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/smartweatherudp/__init__.py", line 6, in <module>
    from pyweatherflowudp.client import EVENT_DEVICE_DISCOVERED, WeatherFlowListener
  File "/usr/local/lib/python3.13/site-packages/pyweatherflowudp/client.py", line 10, in <module>
    from .const import DEFAULT_HOST, DEFAULT_PORT
  File "/usr/local/lib/python3.13/site-packages/pyweatherflowudp/const.py", line 5, in <module>
    import pint
  File "/usr/local/lib/python3.13/site-packages/pint/__init__.py", line 28, in <module>
    from .measurement import Measurement
  File "/usr/local/lib/python3.13/site-packages/pint/measurement.py", line 12, in <module>
    from .quantity import Quantity
  File "/usr/local/lib/python3.13/site-packages/pint/quantity.py", line 69, in <module>
    from .numpy_func import (
    ...<8 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/pint/numpy_func.py", line 875, in <module>
    implement_single_dimensionless_argument_func(func_str)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pint/numpy_func.py", line 864, in implement_single_dimensionless_argument_func
    func = getattr(np, func_str)
  File "/usr/local/lib/python3.13/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
                         "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'cumproduct'. Did you mean: 'cumprod'?
```

I noticed that the [latest updates](https://www.home-assistant.io/blog/2024/12/04/release-202412/) mention Python 3.13, maybe related?

**Comment by jduff001** [comment]
updating to ha core 12.0 on both rpi and ha green versions disabled smartweatherudp.

**Comment by TheBassman** [comment]
Same issue. Running x86 on Intel NUC. Updated core then HA, now won't load

**Comment by beaulebens** [comment]
Downgrading back to HA Core 2024.11.3 "fixed" this, so it definitely seems to be coming from that (not from the HA OS 14 update).

I have Supervisor 2024.11.4 in case that's relevant (and that works).

**Comment by natekspencer** [comment]
This integration has been replaced by the core integration and is no longer maintained. You should completely remove this one.

**Comment by TheBassman** [comment]
If I remember correctly, the core integration requires the cloud and you can't rely on the cloud. I enjoy having all of my data local and getting 3 second updates on wind speed in particular.

**Comment by natekspencer** [comment]
There are two versions available. A local udp implementation based on this integration, and then a cloud version.

**Comment by TheBassman** [comment]
Actually, that is the integration I am running.
I'll try the update again

**Comment by jduff001** [comment]
installing both integrations 'weatherflow' and 'weatherflow forecast' from hacs on ha core 2024.12.0 seems to work.  I deleted all entities from smartweatherudp hubs.  can not seem to be able to delete old integration, so i went into the file editor to remove the custom_components smartweatherudp folder...it says it is not empty...  but i deleted all its files and subdirectories....  oh well.. no harm after clearing the configuration error by "fixing" it after restart.  all works

**Comment by beaulebens** [comment]
I also just removed the custom integration and then used the 'WeatherFlow' one in core now, and it worked, plus I was able to update HA to the latest version and everything keeps working fine. I'll close this since it's no longer relevant.
